In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
np.random.seed(42)
data={
    'student_id':np.arange(1, 301),
    'study_hours':np.random.randint(1, 11, 300),
    'attendance':np.random.randint(50, 101, 300),
    'math_marks':np.random.randint(30, 101, 300),
    'science_marks':np.random.randint(30, 101, 300),
    'english_marks':np.random.randint(30, 101, 300),
    'gender':np.random.choice(['Male', 'Female'], 300)
}

In [4]:
df=pd.DataFrame(data)
df

,student_id,study_hours,attendance,math_marks,science_marks,english_marks,gender
0,1,7,86,58,94,68,Female
1,2,4,73,66,92,83,Female
2,3,8,78,67,46,84,Female
3,4,5,98,37,38,53,Male
4,5,7,95,94,44,51,Female
...,...,...,...,...,...,...,...
295,296,1,58,73,40,63,Male
296,297,5,99,31,69,90,Female
297,298,6,76,42,40,64,Female
298,299,3,51,69,65,93,Male
299,300,9,54,31,88,54,Male

In [6]:
df['Average Marks']=(df['math_marks']+df['science_marks']+df['english_marks'])/3
df

,student_id,study_hours,attendance,math_marks,science_marks,english_marks,gender,Average Marks
0,1,7,86,58,94,68,Female,73.333333
1,2,4,73,66,92,83,Female,80.333333
2,3,8,78,67,46,84,Female,65.666667
3,4,5,98,37,38,53,Male,42.666667
4,5,7,95,94,44,51,Female,63.000000
...,...,...,...,...,...,...,...,...
295,296,1,58,73,40,63,Male,58.666667
296,297,5,99,31,69,90,Female,63.333333
297,298,6,76,42,40,64,Female,48.666667
298,299,3,51,69,65,93,Male,75.666667
299,300,9,54,31,88,54,Male,57.666667

In [7]:
df['Category']=df['Average Marks'].apply(lambda x: 'High' if x>=80 else 'Medium' if x>=60 else 'Low')
df

,student_id,study_hours,attendance,math_marks,science_marks,english_marks,gender,Average Marks,Category
0,1,7,86,58,94,68,Female,73.333333,Medium
1,2,4,73,66,92,83,Female,80.333333,High
2,3,8,78,67,46,84,Female,65.666667,Medium
3,4,5,98,37,38,53,Male,42.666667,Low
4,5,7,95,94,44,51,Female,63.000000,Medium
...,...,...,...,...,...,...,...,...,...
295,296,1,58,73,40,63,Male,58.666667,Low
296,297,5,99,31,69,90,Female,63.333333,Medium
297,298,6,76,42,40,64,Female,48.666667,Low
298,299,3,51,69,65,93,Male,75.666667,Medium
299,300,9,54,31,88,54,Male,57.666667,Low

In [9]:
df['Marks Per Study Hour']=df['Average Marks']/df['study_hours']
df

,student_id,study_hours,attendance,math_marks,science_marks,english_marks,gender,Average Marks,Category,Marks Per Study Hour
0,1,7,86,58,94,68,Female,73.333333,Medium,10.476190
1,2,4,73,66,92,83,Female,80.333333,High,20.083333
2,3,8,78,67,46,84,Female,65.666667,Medium,8.208333
3,4,5,98,37,38,53,Male,42.666667,Low,8.533333
4,5,7,95,94,44,51,Female,63.000000,Medium,9.000000
...,...,...,...,...,...,...,...,...,...,...
295,296,1,58,73,40,63,Male,58.666667,Low,58.666667
296,297,5,99,31,69,90,Female,63.333333,Medium,12.666667
297,298,6,76,42,40,64,Female,48.666667,Low,8.111111
298,299,3,51,69,65,93,Male,75.666667,Medium,25.222222
299,300,9,54,31,88,54,Male,57.666667,Low,6.407407